import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import { TailwindIndicator } from "@/components/tailwind-breakpoint";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/shared/footer";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} ${archivo.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
        <TailwindIndicator />
        <Toaster />
      </body>
    </html>
  );
}
